export const PROJECTS = [
  {
    num: "01",
    title: "Système de suivi étudiant basé sur RFID avec capture photo automatisée et notification par e-mail",
    category: "Python Django",
    desc: "Système de suivi étudiant basé sur la RFID avec capture photo automatisée, notifications par e-mail, export vers Google Drive et rapports administratifs.",
    tech: ["Python Django", "Python", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: ["Meilleur mémoire de fin d'études", "Meilleur système de fin d'études"],
    image: "/images/Capstone/login.png",
    link: "https://github.com/chardoxx-3/RFID-Student-Monitoring-System",
    linkText: "Voir le projet →",
  },
  {
    num: "02",
    title: "ResQR - Système de gestion des secours en cas de catastrophe",
    category: "CodeIgniter 4",
    desc: "Système de gestion des secours en cas de catastrophe basé sur des codes QR pour enregistrer les bénéficiaires, suivre la distribution de l'aide et coordonner les opérations d'urgence.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/ResQR/login.png",
    link: "https://github.com/chardoxx-3/ResQR-Disaster-Relief-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "03",
    title: "iTrak - Système de gestion de terminal",
    category: "CodeIgniter 4",
    desc: "Système de gestion de terminal basé sur la RFID pour suivre la présence des conducteurs, gérer les routes et les files d'attente, traiter les paiements et fournir des analyses opérationnelles en temps réel.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/iTrak/Screenshot%202026-08-14%20175457.png",
    link: "https://github.com/chardoxx-3/iTrak-Terminal-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "04",
    title: "DocuTrack - Système de suivi de documents",
    category: "CodeIgniter 4",
    desc: "Système de suivi de documents pour organiser, archiver, étiqueter et approuver les courriers officiels, avec intégration Google Drive pour un stockage et une synchronisation centralisés.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/Document-Tracking-System-DocuTrack",
    linkText: "Voir le projet →",
  },
  {
    num: "05",
    title: "Système de location de pension de famille",
    category: "CodeIgniter 4",
    desc: "Plateforme web de location de pensions de famille pour gérer les annonces, les réservations, les paiements et les avis, avec des accès distincts pour étudiants, propriétaires et administrateurs.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/BH-Rental-System",
    linkText: "Voir le projet →",
  },
  {
    num: "06",
    title: "PayTrack - Système de gestion de paie employés",
    category: "CodeIgniter 4",
    desc: "Système de gestion de paie basé sur PHP pour gérer la rémunération, les déductions et le traitement de la paie des employés avec un enregistrement centralisé.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/PayTrack-Employee-Payroll-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "07",
    title: "Système de gestion des résidents de Barangay",
    category: "CodeIgniter 4",
    desc: "Système web conçu pour le Barangay Benoni, Mahinog, Camiguin, visant à simplifier les dossiers des résidents, les réservations, les paiements et les rapports.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/Barangay-Residents-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "08",
    title: "Système de gestion des crédits d'une épicerie de quartier",
    category: "CodeIgniter 4",
    desc: "Système web de gestion des comptes de crédit clients, de suivi des dettes impayées, d'enregistrement des paiements et de réservation d'articles pour une épicerie de quartier.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/Sari-Sari-Store-Utang-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "09",
    title: "Système de gestion des employés",
    category: "CodeIgniter 4",
    desc: "Système web de gestion des dossiers employés, de suivi de présence, de traitement de la paie et de gestion des demandes des employés sur une seule plateforme.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/Employee-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "10",
    title: "Système de gestion Motorstar Mambajao",
    category: "CodeIgniter 4",
    desc: "Système de gestion de location de motos avec consultation des véhicules, gestion des réservations, suivi des locations, traitement des paiements et génération de rapports.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/iTrak/Screenshot%202026-08-14%20175457.png",
    link: "https://github.com/chardoxx-3/Motorstar-Mambajao-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "11",
    title: "Système de bibliothèque CPSC",
    category: "CodeIgniter 4",
    desc: "Système de gestion de bibliothèque pour gérer les livres, les membres, les transactions d'emprunt et les amendes avec des flux de catalogue et de circulation rationalisés.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/ResQR/login.png",
    link: "https://github.com/chardoxx-3/CPSC-Library-System",
    linkText: "Voir le projet →",
  },
  {
    num: "12",
    title: "Système de gestion de paie",
    category: "CodeIgniter 4",
    desc: "Système de gestion des employés basé sur le web pour le suivi de présence, le traitement de la paie et la gestion des demandes des employés avec des flux RH centralisés.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/Payroll-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "13",
    title: "Système de gestion de données Barangay",
    category: "CodeIgniter 4",
    desc: "Système web de gestion des dossiers de résidents et des rapports officiels de Barangay avec une saisie simplifiée, un suivi et une génération de documents.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/Barangay-Data-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "14",
    title: "Système d'évaluation et de gestion de la satisfaction client IAS",
    category: "Python Flask",
    desc: "Système web de gestion de enquêtes de satisfaction client pour créer, distribuer et analyser les retours des clients facilement.",
    tech: ["Python Flask", "Python", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/Capstone/login.png",
    link: "https://github.com/chardoxx-3/IAS-Client-Satisfaction-Evaluation-and-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "15",
    title: "DAGAN360 - Système de gestion de course en direct",
    category: "CodeIgniter 4",
    desc: "Système de suivi de checkpoint de course pour gérer les coureurs, les observateurs et la progression en temps réel avec des outils de suivi et de reporting.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/iTrak/Screenshot%202026-08-14%20175457.png",
    link: "https://github.com/chardoxx-3/DAGAN360-Live-Race-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "16",
    title: "Système de gestion OJTrackPro",
    category: "CodeIgniter 4",
    desc: "Système web de suivi de stages pour enregistrer la présence, suivre les heures requises et suivre la progression via des rapports et des tableaux de bord administratifs.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/OJTrackPro-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "17",
    title: "Système de gestion de dossiers PWD",
    category: "CodeIgniter 4",
    desc: "Système centralisant les profils PWD, les services, les rendez-vous, les paiements et les rapports pour améliorer la gestion des dossiers et la qualité de service.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/PWD-Record-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "18",
    title: "Système de gestion d'alliances de mariage",
    category: "CodeIgniter 4",
    desc: "Système de réservation pour gérer l'inventaire d'alliances, les réservations clients, les paiements et le reporting administratif avec des flux de planification de mariage rationalisés.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/DocuTrack/login.png",
    link: "https://github.com/chardoxx-3/Wedding-Ring-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "19",
    title: "Système de gestion de salle de sport",
    category: "CodeIgniter 4",
    desc: "Plateforme web de gestion de salle de sport pour gérer les adhésions, la présence, les paiements, les emplois du temps et les opérations générales.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/BHRental/login.png",
    link: "https://github.com/chardoxx-3/Gym-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "20",
    title: "Système de gestion de location de voitures",
    category: "CodeIgniter 4",
    desc: "Plateforme web de location de voitures pour la consultation et la réservation de véhicules, avec des outils administratifs de gestion des voitures, clients, paiements et rapports.",
    tech: ["CodeIgniter 4", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    awards: [],
    image: "/images/iTrak/Screenshot%202026-08-14%20175457.png",
    link: "https://github.com/chardoxx-3/Car-Rental-Management-System",
    linkText: "Voir le projet →",
  },
  {
    num: "01",
    title: "Collection de créations graphiques",
    category: "Créatif",
    desc: "Une collection d'actifs numériques, de modèles et d'éléments visuels originaux créés pour le marketing, le branding et la production de contenu.",
    tech: ["Créatif", "Design", "Création"],
    awards: [],
    image: "/images/digital/creative.png",
    link: "https://github.com/chardoxx-3/creative-design-assets",
    linkText: "Voir le projet →",
  },
  {
    num: "02",
    title: "Espace de travail créatif",
    category: "Créatif",
    desc: "Un espace de travail numérique conçu pour organiser les ressources créatives, les références et les éléments de design pour une production de contenu efficace.",
    tech: ["Créatif", "Design", "Espace de travail"],
    awards: [],
    image: "/images/digital/workspace.png",
    link: "https://github.com/chardoxx-3/creative-workspace",
    linkText: "Voir le projet →",
  },
  {
    num: "03",
    title: "Système de gestion de contenu",
    category: "Créatif",
    desc: "Un espace de travail structuré conçu pour organiser le contenu, gérer les tâches de production et coordonner le flux de travail de la planification à la publication.",
    tech: ["Créatif", "Espace de travail", "Contenu"],
    awards: [],
    image: "/images/digital/content.png",
    link: "https://github.com/chardoxx-3/content-management-workspace",
    linkText: "Voir le projet →",
  },
  {
    num: "04",
    title: "Planification et programmation de contenu",
    category: "Créatif",
    desc: "Un système de planification visuelle de contenu conçu pour organiser les publications sur les réseaux sociaux, les calendriers et les activités de publication pour une diffusion cohérente.",
    tech: ["Créatif", "Contenu", "Réseaux sociaux"],
    awards: [],
    image: "/images/digital/schedule.png",
    link: "https://github.com/chardoxx-3/content-calendar",
    linkText: "Voir le projet →",
  },
  {
    num: "05",
    title: "Kit de contenu pour réseaux sociaux",
    category: "Créatif",
    desc: "Une collection de modèles pour réseaux sociaux, de graphiques et de cadres de légendes conçus pour maintenir un contenu de marque cohérent et engageant.",
    tech: ["Créatif", "Réseaux sociaux", "Contenu"],
    awards: [],
    image: "/images/digital/social.png",
    link: "https://github.com/chardoxx-3/social-media-content-pack",
    linkText: "Voir le projet →",
  },
];

export const TECHNICAL_CATEGORIES = [
  "TOUS",
  "DÉVELOPPEMENT WEB",
  "BASE DE DONNÉES",
  "PYTHON",
  "SYSTÈMES",
  "QA / TESTS",
  "AUTRES",
];

export const DIGITAL_CATEGORIES = [
  "TOUS",
  "CRÉATIF",
];
